-- CREATE DATABASE Library;

-- USE Library;

CREATE TABLE roles(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role_id INT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE authors(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (100) NOT NULL,
nationality VARCHAR (100) 

);

CREATE TABLE loans(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT ,
book_id INT ,
loan_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
due_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
return_date DATETIME,

FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE TABLE books(
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(225) NOT NULL,
genre VARCHAR(50),
author_id INT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

FOREIGN KEY (author_id) REFERENCES authors(id)
);

CREATE TABLE book_favorite(
id INT,
user_id INT,
book_id INT,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (book_id) REFERENCES books(author_id)
);

